server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: ecommerce
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${AWS_URL}
    username: ${AWS_USERNAME}
    password: ${AWS_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa.hibernate.ddl-auto: none

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  springdoc:
    swagger-ui.path: /swagger-ui.html
    api-docs.path: /v1/api-docs