server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: ecommerce
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:sqlserver://ec2-54-165-28-144.compute-1.amazonaws.com:1433;databaseName=basetesteap;encrypt=false;trustServerCertificate=false
    username: sa
    password: Dev@2024
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa.hibernate.ddl-auto: none

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  springdoc:
    swagger-ui.path: /swagger-ui.html
    api-docs.path: /v1/api-docs